In [1]:
import os, sys
sys.path.append(os.path.abspath(os.path.join("..", "..")))
from instrument.collection import *

I Sat-14:55:56 - ############################################################ startup
I Sat-14:55:56 - logging started
I Sat-14:55:56 - logging level = 10
I Sat-14:55:56 - /home/prjemian/Documents/projects/instrument_poof/instrument/collection.py
I Sat-14:55:56 - /home/prjemian/Documents/projects/instrument_poof/instrument/mpl/notebook.py
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/prjemian/Documents/projects/instrument_poof/instrument/utils/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Sat-14:55:57 - Start soft IOC dockers if PVs not available
I Sat-14:55:57 - /home/prjemian/Documents/projects/instrument_poof/instrument/iocs/check_iocs.py
I Sat-14:55:57 - EPICS IOCs ready...
I Sat-14:55:57 - bluesky framework
I Sat-14:55:57 - /home/prjemian/Documents/projects/instrument_poof/instrument/framework/check_python.py
I Sat-14:55:57 - /home/prjem

In [2]:
print(RE.md["versions"])

{'apstools': '1.3.9', 'bluesky': '1.6.7', 'databroker': '1.1.0', 'epics': '3.4.3', 'event_model': '1.17.0', 'h5py': '2.10.0', 'matplotlib': '3.3.2', 'numpy': '1.19.2', 'ophyd': '1.6.0', 'pyRestTable': '2020.0.3', 'spec2nexus': '2021.1.8'}


In [3]:
selectDiffractometer(fourc)
setEnergy(2800, "eV")
wh()

===================== ========= =========
term                  value     axis_type
===================== ========= =========
diffractometer        fourc              
sample name           main               
energy (keV)          2.80000            
wavelength (angstrom) 4.42801            
calc engine           hkl                
mode                  bissector          
h                     0.0       pseudo   
k                     0.0       pseudo   
l                     0.0       pseudo   
omega                 0         real     
chi                   0         real     
phi                   0         real     
tth                   0         real     
===================== ========= =========



In [4]:
newSample('PrYBCO',3.86,3.86,11.5,90,90,90)

Sample: PrYBCO (current)

======= ===================================================
key     value                                              
======= ===================================================
name    PrYBCO                                             
lattice [3.86, 3.86, 11.5, 90.0, 90.0, 90.0]               
U       [[1. 0. 0.]                                        
         [0. 1. 0.]                                        
         [0. 0. 1.]]                                       
UB      [[ 1.62776821e+00 -9.96720567e-17 -3.34551425e-17] 
         [ 0.00000000e+00  1.62776821e+00 -3.34551425e-17] 
         [ 0.00000000e+00  0.00000000e+00  5.46363940e-01]]
======= ===================================================



In [5]:
setEnergy(1746, "eV")
r1=setor(0,  0, 1, tth=76.25, omega=37.08, chi=89.100, phi=78.9)
r2=setor(-1, 0, 1, tth=150.9, omega=3.760, chi=80.656, phi=78.9)
# fourcSyncToMotor()
calcUB(r1, r2)

[[ 0.23541898 -1.61053782  0.0065016 ]
 [ 0.03089621  0.02408783  0.54620568]
 [-1.61035794 -0.23498313  0.01142993]]


In [6]:
setEnergy(2800)
fourc.calc.wavelength, fourc.calc.energy

(4.428007142857142, 2.8000000000000003)

In [7]:
reflections = ((0,0,1),(-1,0,1))  
cahkl_table(reflections) 

========== ======== ======== ======== ======== ========
(hkl)      solution omega    chi      phi      tth     
========== ======== ======== ======== ======== ========
(0, 0, 1)  0        11.10001 88.62089 29.63225 22.20001
(-1, 0, 1) 0        37.23058 17.46477 -8.03429 74.46116
========== ======== ======== ======== ======== ========



In [8]:
newSample('STO',3.905,3.905,3.905,90,90,90)

Sample: STO (current)

======= ===================================================
key     value                                              
======= ===================================================
name    STO                                                
lattice [3.905, 3.905, 3.905, 90.0, 90.0, 90.0]            
U       [[1. 0. 0.]                                        
         [0. 1. 0.]                                        
         [0. 0. 1.]]                                       
UB      [[ 1.60901032e+00 -9.85234670e-17 -9.85234670e-17] 
         [ 0.00000000e+00  1.60901032e+00 -9.85234670e-17] 
         [ 0.00000000e+00  0.00000000e+00  1.60901032e+00]]
======= ===================================================



In [9]:
listSamples(verbose=False)

STO (current): [3.905, 3.905, 3.905, 90.0, 90.0, 90.0]
main: [1.54, 1.54, 1.54, 90.0, 90.0, 90.0]
PrYBCO: [3.86, 3.86, 11.5, 90.0, 90.0, 90.0]


In [10]:
changeSample('PrYBCO')

Sample: PrYBCO (current)

============ =======================================
key          value                                  
============ =======================================
name         PrYBCO                                 
lattice      [3.86, 3.86, 11.5, 90.0, 90.0, 90.0]   
reflection 1 (h=0.0, k=0.0, l=1.0)                  
reflection 2 (h=-1.0, k=0.0, l=1.0)                 
U            [[ 0.14462684 -0.98941471  0.01189976] 
              [ 0.01898072  0.01479807  0.99971033] 
              [-0.9893042  -0.14435908  0.02092   ]]
UB           [[ 0.23541898 -1.61053782  0.0065016 ] 
              [ 0.03089621  0.02408783  0.54620568] 
              [-1.61035794 -0.23498313  0.01142993]]
============ =======================================



In [11]:
updateSample(3.8,3.8,11.5,90,90,90)

PrYBCO (current): [3.8, 3.8, 11.5, 90.0, 90.0, 90.0]


In [12]:
cahkl(0,0,1)

PosCalcE4CV(omega=11.100004855757552, chi=88.62089333948501, phi=29.632172350669897, tth=22.200009711515104)

In [13]:
# to get a preview of a given hkl scan 
# (and make sure all reflections are reachable)
scanhkl_test((0,0,0.9),(0,0,1.1),10,E=2800) 

NameError: name 'scanhkl_test' is not defined

In [ ]:
h=0.995
q=1.005
scanhkl((h,h,h),(q,q,q),30,1,E=2831.75)

In [ ]:
mydata=mdaFile('mydata',191,204)  # load data

In [ ]:
mydata.updateFiles(mydata.scanNum[-1]) # load more data

In [ ]:
plot_hkl(mydata,216,218,det=34)

In [ ]:
plot_hkl(mydata,229,det=34)

In [ ]:
fit_hkl_gauss(202,34,0.001)  # scan, det, FWHM_guess

In [ ]:
pwd

In [ ]:
Macros_29id